### ISSUE TITLE
AttributeError in Thread url

### ISSUE THREAD

**Issue by arthur-wsw** [pinax/pinax-messages#11]
There is an attribute error when trying to access thread from url schema.

> builtins.AttributeError
AttributeError: Generic detail view ThreadView must be called with either an object pk or a slug.

**Comment by SudShekhar** [comment]
I haven't confirmed this from actual tests but you should also change the `thread_id` to `pk` in the tests, since the below lines would fail IMO

    response = self.get("messages_thread_detail", thread_id=thread_id)

Another option might be to define the `pk_url_kwarg` on the template and keep `thread_id` as it is in the `urls.py`.
