### ISSUE TITLE
Update package documentation to reference new URL scheme

### ISSUE THREAD

**Issue by vin0110** [pinax/pinax-messages#24]
The package installed my pip (0.2) uses the old URL scheme, ie, patterns.
```
/Users/vin/Envs/gim-web/lib/python3.5/site-packages/pinax/messages/urls.py:11: RemovedInDjango110Warning: django.conf.urls.patterns() is deprecated and will be removed in Django 1.10. U
pdate your urlpatterns to be a list of django.conf.urls.url() instances instead.
  url(r"^thread/(?P<thread_id>\d+)/delete/$", views.thread_delete, name="messages_thread_delete"),
```
The code in this repo uses the new scheme.

**Comment by vleong2332** [comment]
Like the OP said, the code in `master` already uses a list of `django.conf.urls.url()` instead of `django.conf.urls.patterns()`. Is this a matter of doing a new release?

**Comment by grahamu** [comment]
Resolved by https://github.com/pinax/pinax-messages/pull/26. Thanks @vleong2332
