### ISSUE TITLE
Outdated pypi package

### ISSUE THREAD

**Issue by senoadiw** [pinax/pinax-messages#25]
Greetings,

I would like to use this app independently but doing `pip install pinax-messages` installs an outdated version of pinax-messages.  Also it seems the necessary templates are missing in https://github.com/pinax/pinax-theme-bootstrap/tree/master/pinax_theme_bootstrap/templates/pinax?

Regards,

SN

**Comment by vleong2332** [comment]
Regarding the outdated version, this sounds like it's related to #24.

**Comment by jtauber** [comment]
We've released 0.3.0 to PyPI and the templates will be in the next release of PTB.
