### ISSUE TITLE
Sending message to self shows duplicated threads

### ISSUE THREAD

**Issue by vleong2332** [pinax/pinax-messages#29]
Somewhat related to #28, the result of sending a message to self is two identical threads shown on the thread list for the same user.

**Comment by jtauber** [comment]
Is this irrelevant once #30 lands?

**Comment by vleong2332** [comment]
No. I created this in case #28 is not a legitimate bug and #30 doesn't land. Probably should've said that in the original comment,

**Comment by grahamu** [comment]
My feeling is we should fix issue #28 and close this one. If you cannot send a message to yourself then presumably duplicate identical threads won't appear.
