### ISSUE TITLE
pinax messages error in admin

### ISSUE THREAD

**Issue by myimages** [pinax/pinax-messages#36]
Hi , 

I followed the installation instructions  to install pinax messages and I have this error when trying to create a new user in admin.

no such table: account_account

does it require [django-user-accounts](https://github.com/pinax/django-user-accounts) to be in installed apps ?

I am using [django-registration ](https://github.com/ubernostrum/django-registration) because it is simple , and  i want to use pinax-massages because it is also simple and I like to keep things simple.

thank you.

**Comment by myimages** [comment]
@grahamu 

if I remove the url line from my url.py every thing start working in the admin again.

`url(r"^messages/", include("pinax.messages.urls", namespace="pinax_messages")),`

**Comment by KatherineMichel** [comment]
Closing issue. Although it would not be required to use django-user-accounts, Pinax apps are already set up to use it. django-registration would have required it's own setup.
