### ISSUE TITLE
Django 3 Support

### ISSUE THREAD

**Issue by maddrum** [pinax/pinax-messages#50]
Since Django 3 dropped support for python 2, pinax messages do not work.

Problem is in models definition which is using @python_2_unicode_compatible decorator and referring to the __future__ library. 

Support for both is now over and I think they should be removed.

**Comment by KatherineMichel** [comment]
Hi @maddrum, you're absolutely right. This is something I'm working on a release plan for. Thank you! https://github.com/pinax/pinax/wiki/Pinax-20.xx-Proposed-Process

**Comment by KatherineMichel** [comment]
@maddrum We're working on a new release now, including dropping support for Python 2. Would you be interested in updating this app to drop Python 2/add Django 3? Here's  summary of what we're dropping/adding: https://github.com/pinax/pinax/wiki/Pinax-20.xx-Proposed-Process#pinax-20xx-release-overview

**Comment by KatherineMichel** [comment]
An update, @maddrum... It's just a matter of time before the PR below will be merged and provide Django 3.0 support. https://github.com/pinax/pinax-messages/pull/51

**Comment by KatherineMichel** [comment]
Hello @maddrum, I've just merged that PR and should just be a matter of time before it's published to PyPI. Cheers.

**Comment by chemeng** [comment]
Pypi still hasn't released v3. Any idea why it's taking so long?

**Comment by KatherineMichel** [comment]
@chemeng It's because I don't personally have access to do it. I've asked the people above me about getting them published.

**Comment by Flexin1981** [comment]
@KatherineMichel is there an update you can provide on this ?

Would be useful if there is a workaround way of getting the latest branch listed in the readme.

Thanks

**Comment by KatherineMichel** [comment]
@Flexin1981 I've been given access recently and will be publishing soon! Sorry for the delay.

**Comment by krystofbe** [comment]
@KatherineMichel any update on this? :) thanks

**Comment by KatherineMichel** [comment]
Hello, @maddrum, @chemeng, @Flexin1981, @krystofbe... I've published a release earlier today. Hope this helps! https://pypi.org/project/pinax-messages/
