### ISSUE TITLE
Why the new version not on pypi?

### ISSUE THREAD

**Issue by tiagoarasilva** [pinax/pinax-messages#56]
**Ask a question**
Why the new version is not on pypi? I'm trying to upgrade to django 3 and I can't for this reason, unfortunately.

**Comment by PeterMarchev** [comment]
> Why the new version is not on pypi? I'm trying to upgrade to django 3 and I can't for this reason, unfortunately.

https://github.com/pinax/pinax-messages/issues/50
Apparently it's coming "soon".

**Comment by tiagoarasilva** [comment]
@PeterMarchev thank you very much

**Comment by morenoh149** [comment]
please close if your issue is resolved.

**Comment by KatherineMichel** [comment]
Hello, @tiagoarasilva, @PeterMarchev, @morenoh149... I've published a release earlier today. Hope this helps! https://pypi.org/project/pinax-messages/
