### ISSUE TITLE
Pagination in thread view?

### ISSUE THREAD

**Issue by reedjones** [pinax/pinax-messages#57]
In the thread_detail and inbox views, how could we add pagination? 
Right now in thread_detail.html it goes through all the messages, but what if the inbox has hundreds of messages in it?

**Comment by morenoh149** [comment]
if answered in https://github.com/pinax/pinax-messages/issues/55 please close

**Comment by KatherineMichel** [comment]
Will assume answered. Feel free to re-open if needed or comment on other issue.
